[package]
name = "ruler"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
symbolic_expressions = "5"
env_logger = { version = "*", default-features = false }
log = "*"
egg = { git = "https://github.com/egraphs-good/egg", rev = "39415f19acdacd6dde62f40cb2bb08f8669acc85" }
rand_pcg = "0.2"
rand = { version = "0.7", default-features = false, features = ["std"] }
indexmap = "*"
