[package]
name = "ruler"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>", "Chandrakana Nandi <cnandi@cs.washington.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = { version = "0.7", default-features = false }
rand_pcg = "0.2"
rand = { version = "0.7", default-features = false, features = ["std"] }

# egg = "0.5"
egg = { git = "https://github.com/mwillsey/egg", rev = "6e80da67aeabaf5692ca9a339495b073ef73322f" }
# egg = { path = "/Users/mwillsey/src/egg" }

[dev-dependencies]
ordered-float = "1.0"
num-bigint = { version = "0.3", features = ["rand"] }
num-rational = "0.3"
