[package]
name = "ruler"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>", "Chandrakana Nandi <cnandi@cs.washington.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = { version = "0.7", default-features = false }
rand_pcg = "0.2"
rand = { version = "0.7", default-features = false, features = ["std"] }

egg = { path = "/Users/cnandi/research/egg" }
# egg = "0.6"
indexmap = "1"
