[package]
name = "ruler"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.19", features = ["derive"] }
rayon = "1.5"
structopt = { version = "0.3", default-features = false }
symbolic_expressions = "5"
env_logger = { version = "*", default-features = false }
log = "*"
rand_pcg = "0.2"
rand = { version = "0.7", default-features = false, features = ["std"] }
indexmap = "*"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

regex = "1"
itertools = "0.9"

[dependencies.egg]
features = ["serde"]
# git = "https://github.com/egraphs-good/egg"
# rev = "e5213a5e5e77b31f3eab85f1515c1c3be9c3f560" # eclasses
# rev = "8f4bf69ed139aa3d8683f54cc8c0884a984fc4a8" # rules
# rev = "dc99befe30f25c6bce05d10febd10d9228619a8f" # master
path = "../egg"
